### ISSUE TITLE
"UnboundLocalError" during Step 2 when running LDpred-funct

### ISSUE THREAD

**Issue by rbpeng** [carlaml/LDpred-funct#4]
Thanks for the work you've done developing and maintaining LDpred-funct! I'm running to an issue when running LDpred-funct that occurs during "Step 2: Compute posterior mean effect sizes" after  the coordination step. In particular, I'm running into `UnboundLocalError: local variable 'ldpred_effect_sizes' referenced before assignment` when trying to calculate posterior means for chromosome 1. This error seems to be coming from `line 298   ldpred_effect_sizes.extend(updated_betas) in LDpredfunct_bayes_shrink.py`. I'm not sure what is causing this error or how to resolve it, and I'd appreciate any help in fixing this issue.

I've attached the log file in case it would be helpful for you to figure out what the issue is. Thank you so much!
[LDpred_funct.log](https://github.com/carlaml/LDpred-funct/files/3334877/LDpred_funct.log)

**Comment by carlaml** [comment]
Dear Robert, 
First, apologies for not seeing this message earlier. For some reason, I'm not getting the email notifications. 

Thanks for your interest in using our software. I think the issue is becuase you are missing the flag: --posterior_means="name_for_file_of_posterior_betas"

**Comment by carlaml** [comment]
Another comment I wanted to mention is that I noticed that you are including imputed genotypes and also the the functional enrichments file includes imputed data (intersection of boths has 4,618,346 SNPs). But the summary statistics file only includes genotyped SNPs (665543 SNPs parsed from summary statistics file). In my paper, I pointed out that there is a limited improvement compared to other methods that do not use functional information when only considering genotyped SNPs, given that functional information is far less useful when restricting to genotyped variants, likely because tagging variants may not belong to enriched functional annotations. 
Best,
Carla

**Comment by rbpeng** [comment]
Hey Carla, thanks for the help! It ended up being a silly mistake by me since I had `outLDpredfunct="results/post_mean_test"` but I had the flag as `--posterior_means=${outLdpredfunct}`. After fixing this, LDpred-funct finished running without any issues. 

Also, thank you for the comment about using LDpred-funct when only considering genotyped SNPs. I think the original ssf I used had imputed genotypes, but LDpred for some reason only parsed 665,543 of the SNPs from the original ssf. I'll take a closer look into this.
